print("##############################")
print("#                            #")
print("#   Muhammad Naufal Khalish  #")
print("#        2410817110004       #")
print("#                            #")
print("##############################")