Nama=input("Nama :")
NIM=input("NIM :")
Kelas_Paralel=input("Kelas Paralel :")
TempatTanggal_Lahir=input("Tempat/Tanggal Lahir :")
Alamat=input("Alamat :")
Hobby=input("Hobby :")
No_Hp=input("No.HP :")

print("Nama : ", Nama)
print("NIM : ",NIM)
print("Kelas_Paralel : ",Kelas_Paralel)
print("Tempat/Tanggal Lahir : ",TempatTanggal_Lahir)
print("Alamat : ",Alamat)
print("Hobby : ",Hobby)
print("No. HP : ",No_Hp)
print("")